### PR TITLE
Added isort to sort the scripts

### PR DESCRIPTION
**Pull request by a-mere-peasant**

### CODE REVIEW

**Comment by ahawker** [comment]
I'm trying to rebase your branch with the latest master but don't have push access to your master branch. Can you allow that so I can clean this up and get it merged?

**Comment by a-mere-peasant** [comment]
Sure , sorry for replying late.

**Comment by ahawker** [comment]
I was able to rebase the PR branch on the fork with latest master.

1) I removed the verbose flag in the isort config as it's a bit spammy.
2) I applied the isort changes `isort --recursive crython tests`

**Comment by ahawker** [comment]
Apologies for the merge delay; thank you very much for the contribution @a-mere-peasant

**Pull request merged**
